version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-backend:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd ecoupon-manager-backend
            npm install
            npm run build
      - save_cache:
          paths: [ecoupon-manager-backend/node_modules]
          key: backend-build

workflows:
  default:
    jobs:
      - build-backend